services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: Paalito10&
      REDMINE_SECRET_KEY_BASE: Paalito10&

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Paalito10&
      MYSQL_DATABASE: redmine
